# Cloudflare Workers configuration for Next.js with next-on-pages
name = "zenow-learn-admin"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://zenow-learn-backend-710009987783.asia-south1.run.app"
NODE_ENV = "production"
